### ISSUE TITLE
The source code of hookv

### ISSUE THREAD

**Issue by twmht** [crizCraig/deepdrive#2]
Hi,

The hookv used in deepdrive is a bridge between GTAV and caffe.

Do you have any plan to distribute the  work of the hookv?

Thanks

**Comment by crizCraig** [comment]
All the source is in these repos: https://github.com/crizCraig?page=1&tab=repositories&utf8=%E2%9C%93&q=deepdrive

**Comment by twmht** [comment]
@crizCraig 

thanks for your reply.

My concern is that hookv in the repository https://github.com/crizCraig/deepdrive-scripthookv seems not up to date?

Since the ScriptHookV.lib in the repo is different from the ones in google-drive.

**Comment by tyluckyma** [comment]
@crizCraig 

May I ask how scriptHookV is linked to your program? Seems like in the installation instruction, it is not required to install scriptHookV under the GTAV directory. Do you plan to use it in the Reinforcement Learning version? Just to help get reward?
